In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

A = np.array([[1,-1,0],[-2,-4,1],[0,1,1]])
eigvals, eigvecs = la.eig(A)
print("Eigenvalues: " + str(eigvals))
eigvals = eigvals.real
print("Real Eigenvalues: " + str(eigvals))
print("Eigenvectors: \n" + str(eigvecs))

maxval = abs(eigvals[0])
col = 0
for i in range(0, len(eigvals)):
     if(abs(eigvals[i]) > maxval):    
       maxval = eigvals[i];
       col = i;
maxvec = eigvecs[:,col].reshape(3,1)
print("Dominant Eiganvalue: " + str(maxval))
print("Dominant Eiganvector: \n" + str(maxvec))

Eigenvalues: [-4.54138127+0.j  1.54138127+0.j  1.        +0.j]
Real Eigenvalues: [-4.54138127  1.54138127  1.        ]
Eigenvectors: 
[[ 1.74855890e-01 -6.60372686e-01  4.47213595e-01]
 [ 9.68943154e-01  3.57513400e-01  7.41055684e-18]
 [-1.74855890e-01  6.60372686e-01  8.94427191e-01]]
Dominant Eiganvalue: 4.541381265149109
Dominant Eiganvector: 
[[ 0.17485589]
 [ 0.96894315]
 [-0.17485589]]


Assignment 2 Analysis
- Above show the eigenvalues and eigenvectors for the three dimensioanl difference equation
- The eigenvalues do correspond to their eigenvectorsas seen above in the matrix
- The dominant eigenvalue would be 4.54138126.. because its absolute value is greater than the other values. So the corresponding eigenvector to that eigenvalue will be the dominant eigenvector. 
- Since the absolute value of the dominant eigenvalue is greater than 1 the system will diverge to infinity. The stability of this system is proven to be unstable. 
- Since the magnitude of the dominant eigenvector is less then 1 then the component is shrinking. This is a similar interpretation from the absolute value from the eigenvalue.
